import "./globals.css";
import Header from "./components/Header";
import { ThemeProvider } from "next-themes";
import ThemeCom from "./components/ThemeCom";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeModeScript } from "flowbite-react";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";
import { GlobalProvider } from "@/context/GlobalContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GlobalProvider>
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <head>
            <ThemeModeScript />
          </head>

          <body className="relative">
            <ThemeProvider>
              <ThemeCom>
                <Header />
                {children}
                <Footer />
                <ToastContainer />
              </ThemeCom>
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </GlobalProvider>
  );
}
